apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bare-beaver-java-quarkus 
  janus-idp.io/tekton: bare-beaver-java-quarkus
  backstage.io/kubernetes-id: bare-beaver-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: bare-beaver-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  