apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bare-beaver-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bare-beaver-java-quarkus-gitops